### ISSUE TITLE
Translations are not done

### ISSUE THREAD

**Issue by hoshster** [jashjacob/MiWIFI-Router-Mac-App-English-Translation#2]
Tried the instructions but still the app shows chinese language. Please support immeditely.

**Comment by jashjacob** [comment]
Share a screenshot of your updated file.

**Comment by jashjacob** [comment]
Kindly check the update en.lproj file for translation.

**Comment by hoshster** [comment]
Still the code is not working for my router! Please update further instructions...

**Comment by jashjacob** [comment]
> Still the code is not working for my router! Please update further instructions...

Can you share your /Applications/XMRouter.app/Contents/Resources/ folder screeenshot?

**Comment by jashjacob** [comment]
@hoshster Hi, Can you share you folder screenshot?
