### ISSUE TITLE
No translations to be seen anywhere

### ISSUE THREAD

**Issue by madrulane** [jashjacob/MiWIFI-Router-Mac-App-English-Translation#3]

**Comment by jashjacob** [comment]
Can you walk me through what you’ve done? Can you share a screenshot of your updated file?

**Comment by madrulane** [comment]
I did overwrite the files in zh-Hans.lproj folder (as can be seen by the date) and nothing happened...
![screen shot 2019-01-30 at 13 09 46](https://user-images.githubusercontent.com/21111550/51977735-da6d5680-2490-11e9-81be-bd1e48866046.png)
![screen shot 2019-01-30 at 13 08 27](https://user-images.githubusercontent.com/21111550/51977736-da6d5680-2490-11e9-8a4a-65f9cd4c5ef9.jpg)
![screen shot 2019-01-30 at 13 09 54](https://user-images.githubusercontent.com/21111550/51977737-db05ed00-2490-11e9-9098-a1885ee23056.png)

**Comment by jashjacob** [comment]
Found the issue. Please check if there is another .lproj folder in your directory. In the latest update, they've change the localization folder to **en.lproj folder.** I am updating the Git Folder to reflect the same.

**Comment by jashjacob** [comment]
@mardulas Hi, Did it work for you now?
