### ISSUE TITLE
is it possible to access usb files by using this app? 

### ISSUE THREAD

**Issue by thanhbinh84** [jashjacob/MiWIFI-Router-Mac-App-English-Translation#4]
It shows the usb capacity but I don't know how to retrieve the files. 
What is the purpose of the app? 
![Screen Shot 2020-04-19 at 14 46 24](https://user-images.githubusercontent.com/366768/79682712-9f4e7300-824e-11ea-8584-30f1dcf5ac77.png)

**Comment by jashjacob** [comment]
Have you tried clicking on "Router Files"?

**Comment by thanhbinh84** [comment]
Yes, it shows error below: 
![Screen Shot 2020-04-20 at 14 06 09](https://user-images.githubusercontent.com/366768/79723511-1861cf00-8310-11ea-8f70-db3873bc266e.png)

**Comment by jashjacob** [comment]
That is strange. 
Are you able to access the files through the miwifi.com (router accesss page) or the MiWifi Mobile App?

**Comment by thanhbinh84** [comment]
On web: 
![Screen Shot 2020-04-20 at 14 22 17](https://user-images.githubusercontent.com/366768/79724797-58c24c80-8312-11ea-8fd8-b937304954e1.png)
On mobile, I can use mi wifi app and access all files. 
How to access file via miwifi.com? It is just the web site to download client, isn't it?

**Comment by thanhbinh84** [comment]
It works now, I have to go to Mi Wifi app and allow storage access for my macbook 
![2020-04-21 08 22 54](https://user-images.githubusercontent.com/366768/79815166-2fed9600-83aa-11ea-855e-f5735df92767.jpg)
