### ISSUE TITLE
The client is not downloadable anymore

### ISSUE THREAD

**Issue by undefinedplayer** [jashjacob/MiWIFI-Router-Mac-App-English-Translation#5]
When I try to download the link http://bigota.miwifi.com/xiaoqiang/client/xqmac_client.dmg. I get access denied. Is it not available anymore or I missed something?

**Comment by jashjacob** [comment]
I think the support ended for the Mac App. I have added the .dmg file in this repo.

Link - https://github.com/jashjacob/MiWIFI-Router-Mac-App-English-Translation/commit/4b1a9d7043a5d3f65f0d4001709475bbbf829214
