### ISSUE TITLE
After mentioned steps, app becomes unusable

### ISSUE THREAD

**Issue by MBilalShafi** [jashjacob/MiWIFI-Router-Mac-App-English-Translation#7]
I have downloaded the attached dmg and followed the mentioned steps yet I couldn't open the app, rather it says app is damaged.

Mac OS Version: 11.1 Big Sur

<img width="452" alt="image" src="https://user-images.githubusercontent.com/12609561/103341643-4e636f80-4aa9-11eb-8854-55f9d2359759.png">

**Comment by jashjacob** [comment]
The app is not under active development by the team. Will reopen the issue if there's a BigSur Update pushed out.

**Comment by HyungJu** [comment]
`xattr -cr /Applications/XMRouter.app`
Run this command in your terminal.
I think the app isn't maintained anymore but it's still compatible with Big Sur.
