### ISSUE TITLE
Updated cdn link

### ISSUE THREAD

**Issue by HyungJu** [jashjacob/MiWIFI-Router-Mac-App-English-Translation#8]
bigota.miwifi is no more working.
For someone looking for MiWIFI app for mac from official link, check out this link : [this](http://cdn.cnbj1.fds.api.mi-img.com/xiaoqiang/client/xqmac_client.dmg)

You can download other miwifi files by replacing bigota domain into `http://cdn.cnbj1.fds.api.mi-img.com`

**Comment by HyungJu** [comment]
I found there's an installation file already inside this repository. closing issue!

**Comment by jashjacob** [comment]
@HyungJu Do you know the official websute for the MiWifi App?
Are they actively developing & distrbuting the app?
